ToDoList/Models/Item.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
  public class Item
  {
    public int ItemId { get; set; }
    [Required(ErrorMessage = "The item's description can't be empty!")]
    public string Description { get; set; }
    [Range(1, int.MaxValue, ErrorMessage = "You must add your item to a category. Have you created a category yet?")]
    public int CategoryId { get; set; } //foregin key in items db
    public Category Category { get; set; } //nav prop creates 1:many
    public List<ItemTag> JoinEntities { get; } //collection nav prop.
    public bool isComplete { get; set; } = false;
    public ApplicationUser User { get; set; }
  }
}

ToDoList/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Controllers
{
  public class CategoriesController : Controller
  {
    private readonly ToDoListContext _db;
    public CategoriesController(ToDoListContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Category> model = _db.Categories.ToList(); //getall w linq
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Category category)
    {
      _db.Categories.Add(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Category thisCategory = _db.Categories
      .Include(category => category.Items) //want to incl. items prop
      .ThenInclude(item => item.JoinEntities)
      .ThenInclude(join => join.Tag)
      .FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }
    public ActionResult Edit(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }
    [HttpPost]
    public ActionResult Edit(Category category)
    {
      _db.Categories.Update(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteCofirmed(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      _db.Categories.Remove(thisCategory);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

ToDoList/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace ToDoList.Controllers
{
  [Authorize]
  public class ItemsController : Controller
  {
    //hold db connection as todoliscontext type
    private readonly ToDoListContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public ItemsController(UserManager<ApplicationUser> userManager, ToDoListContext db) //passed as arg thru dependency injection. this arg is same todolistcontext setup as service in program.cs
    {
      _userManager = userManager;
      _db = db; //set value of _db prop to Todolistocntext dbl.
    }
    public async Task<ActionResult> Index()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Item> userItems = _db.Items
              .Where(entry => entry.User.Id == currentUser.Id)
              .Include(item => item.Category) //includes category w/item
              .ToList(); //replaces getall() uses linq
      return View(userItems);
    }
    public ActionResult Create() //replaces the New()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name"); //selectlist provides data needed to create html sleect of all categories from db.
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create(Item item, int CategoryId)
    {
      if (!ModelState.IsValid) //model validation don't want categoryId to =0/not exist. ea item Needs a category.
      {
        ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
        return View(item);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        item.User = currentUser;
        _db.Items.Add(item);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
    }
    public ActionResult Details(int id) //id match param from actionlink in index.
    {
      Item thisItem = _db.Items
      .Include(item => item.Category)
      .Include(item => item.JoinEntities) //fetch join.ent
      .ThenInclude(join => join.Tag) //fetch tag object
      .FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }
    //line 36 same code: Item thisItem = _db.Items.FirstOrDefault(thing => thing.ItemId == id);
    public ActionResult Edit(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisItem);
    }
    [HttpPost]
    public ActionResult Edit(Item item)
    {
      _db.Items.Update(item);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    { //gets item from db return to view
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }
    [HttpPost, ActionName("Delete")] //need this b/c both get/post take id as parameter. c# no allow two method w/same signature.
    public ActionResult DeleteConfirmed(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      _db.Items.Remove(thisItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddTag(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
      ViewBag.TagId = new SelectList(_db.Tags, "TagId", "Title");
      return View(thisItem);
    }
    [HttpPost]
    public ActionResult AddTag(Item item, int tagId)
    {
      #nullable enable
      ItemTag? joinEntity = _db.ItemTags.FirstOrDefault(join => (join.TagId == tagId && join.ItemId == item.ItemId));
      #nullable disable
      if (joinEntity == null && tagId != 0)
      {
        _db.ItemTags.Add(new ItemTag() { TagId = tagId, ItemId = item.ItemId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = item.ItemId });
    }
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      ItemTag joinEntry = _db.ItemTags.FirstOrDefault(entry => entry.ItemTagId == joinId);
      _db.ItemTags.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult MarkAsComplete(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
      thisItem.isComplete = true;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = id });
    }
  }
}

ToDoList/Views/Items/AddTag.cshtml
@{
  Layout = "_Layout";
}
@model ToDoList.Models.Item

<h2>Add a tag</h2>

<h4>Add a tag to this item: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ItemId)

  @Html.Label("Select tag")
  @Html.DropDownList("TagId")

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}
@model ToDoList.Models.Item
<h4>Add a new item</h4>

<p>@Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

<p>@Html.ValidationMessageFor(model => model.Description, "", new
    {
      @class = "text-danger",
      @style = "font-weight: 600;"
    })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description) //for new item
  <br />
  @Html.LabelFor(model => model.Category) //dropdown cat. names
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Add new item" class="btn btn-primary"/>
}
<br />
<p>@Html.ActionLink("Add category", "Create", "Categories")</p>
<p>@Html.ActionLink("Show all items", "Index")</p>

ToDoList/Views/Items/CreateForm.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>My To-Do List!</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
  <form action="/items" method="post">
    <label for="description">Add a new item</label>
    <input id="description" name="description" type="text">
    <button type="submit">Submit</button>
  </form>
</body>

</html>

ToDoList/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Items/Details.cshtml
@{
  Layout = "_Layout";
}
@using ToDoList.Models
@model ToDoList.Models.Item

<h2>Item Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
@* // *@
<hr />
@if (Model.isComplete)
{
  <h3>Status: Completed</h3>
}
else
{
  <div id="notWatched">
  <h3>Status: Not completed</h3>

  @using (Html.BeginForm("MarkAsComplete", "Items", new { id = Model.ItemId }))
    {
      <label>Mark as </label>
      <input type="submit" value="complete" />
    }
  </div>
}
<hr />
<h3>@Html.DisplayNameFor(model => model.Category): @Html.DisplayFor(model => model.Category.Name)</h3>


@if (@Model.JoinEntities.Count == 0)
{
  <p>This item does not have any tags yet!</p>
}
else
{
  <h4>This item has the following tags:</h4>
  <ul>
  @foreach (ItemTag join in Model.JoinEntities)
    {
      <li>Tag: @join.Tag.Title</li>
      @using (Html.BeginForm("DeleteJoin", "Items"))
      {
        @Html.Hidden("joinId", @join.ItemTagId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}


<p>@Html.ActionLink("Back to list", "Index")</p>
@* edit link, specify looking for itemid of model passed in this view *@
<p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.ItemId })</p>
<p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.ItemId })</p>
<p>@Html.ActionLink("Add a Tag", "AddTag", new { id = Model.ItemId })</p>

ToDoList/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<h2>Edit</h2>

<h4>Edit this item: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{ //need to pass spec. items id on the controller so it knows who to update
  @Html.HiddenFor(model => model.ItemId) 

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Category) //cat to associate item with
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Save" /> //button. text='save'
}
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}
@using ToDoList.Models;

<h1>Items for @User.Identity.Name</h1>
@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
}
else
{
<ul>
  @foreach(Item item in Model)
  {
    <li>@Html.ActionLink($"{item.Description}", "Details", new { id = item.ItemId }) | @item.Category.Name</li>
    //link will route to Details action in ItemsController
  }
</ul>
}
<p>@Html.ActionLink("Add new item", "Create")</p>
<p>@Html.ActionLink("See all categories", "Index", "Categories")</p>
<p>@Html.ActionLink("go home", "Index", "Home")</p>